import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const glowSans = localFont({
  src: [
    {
      path: '../public/fonts/GlowSansTC-Normal-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/GlowSansTC-Normal-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  // 定義一個 CSS 變數名稱，方便 Tailwind 使用
  variable: '--font-glow-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${glowSans.variable} ${glowSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
