import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';

import './globals.css';

const glowSans = localFont({
  src: [
    {
      path: '../../public/fonts/GlowSansTC-Normal-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/GlowSansTC-Normal-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  // 定義一個 CSS 變數名稱，方便 Tailwind 使用
  variable: '--font-glow-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-hant">
      <body className={`${glowSans.variable} antialiased flex flex-col h-screen`}>
        <header className="h-16 border-b-2 border-gray-100">
          <div></div>
          <Link href={'/'}>
            <h1>Ted Yin</h1>
          </Link>
        </header>
        <main className="flex-1 overflow-y-auto">{children}</main>
        <aside className="border-t-2 border-gray-100 h-14 block md:hidden"></aside>
      </body>
    </html>
  );
}
